### ISSUE TITLE
Update new API

### ISSUE THREAD

**Issue by TNAJanssen** [staticall/ODR_RestApi_Examples#1]
When are you going to update the scripts for the new API or do you need some help?

**Comment by harmise** [comment]
Hoi

morgenochtend gaan we om 9 uur de update doen en zal 1-2 uur in beslag 
nemen

na deze update volgt SSL certificaten is al af maar installeren we pas 
later ( deze week)

en gaan we verder met o.a domeinnamen en de rest

hopende u zo voldoende geïnformeerd te hebben

Vriendelijke groet
H van der Horst

Internet Service Europe

Internet Service Europe BV
Netherlands
Phone: +31 (0) 165 318788
Fax :    +31 (0) 165 317438
e-mail: harm@i-s-e.nl
www:    www.i-s-e.nl

# 

De informatie verzonden met dit e-mail bericht is uitsluitend bestemd voor
de geadresseerde. Gebruik van deze informatie door anderen dan de
geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding
en/of verstrekking van deze informatie aan derden is niet toegestaan.
Internet Service Europe BV staat niet in voor de juiste en volledige
overbrenging van de inhoud van een verzonden e-mail, noch voor tijdige
ontvangst daarvan. Deze e-mail voor verzending gecontroleerd op
de aanwezigheid van virussen.

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the sender by
replying the email and please remove the files from your computer. This
footnote also confirms that this email message has been swept for the

# presence of computer viruses.

Op 17-aug-2015 om 14:18 schreef Alexander Janssen:

**Comment by staticall** [comment]
Hello, Alexander!

Files actually are updated, only they're stored in a branch ["UnifiedContacts"](https://github.com/staticall/ODR_RestApi_Examples/tree/UnifiedContacts)
Update to the live app should happen tomorrow in the morning, then the branch will be merged into master

At the moment, new contacts are installed on new test version www.odrregistry.nl, you can check your code there, just in case! Test version will remain after update is installed.
Docs for this repo will be updated later tomorrow, they will match [this](http://old.odrregistry.nl/?rm=api2doc)

And thank you for offering, by the way, we plan on updating API for completely new version later this year (changes should mostly be inside our code and API methods should remain the same, at least that's the idea), then we might need your help! ;)
